import {createTheme} from '@fluentui/react';

export const mainTheme = createTheme({
	palette: {
		themePrimary: '#0f0f0f',
		themeLighterAlt: '#e2e2e2',
		themeLighter: '#c8c8c8',
		themeLight: '#aeaeae',
		themeTertiary: '#939393',
		themeSecondary: '#797979',
		themeDarkAlt: '#5e5e5e',
		themeDark: '#444444',
		themeDarker: '#2a2a2a',
		neutralLighterAlt: '#faf9f8',
		neutralLighter: '#f3f2f1',
		neutralLight: '#edebe9',
		neutralQuaternaryAlt: '#e1dfdd',
		neutralQuaternary: '#d0d0d0',
		neutralTertiaryAlt: '#c8c6c4',
		neutralTertiary: '#a19f9d',
		neutralSecondary: '#605e5c',
		neutralSecondaryAlt: '#8a8886',
		neutralPrimaryAlt: '#3b3a39',
		neutralPrimary: '#323130',
		neutralDark: '#201f1e',
		black: '#000000',
		white: '#ffffff',
	},
	semanticColors: {
		buttonBorder: '#eaeaea',
		buttonText: '#888',
		inputBorder: '#eaeaea',
		inputIcon: '#eaeaea',
		focusBorder: 'red',
		smallInputBorder: '#666',
	},
});

export const myTheme = createTheme({
	palette: {
		themePrimary: '#0078d4',
		themeLighterAlt: '#eff6fc',
		themeLighter: '#deecf9',
		themeLight: '#c7e0f4',
		themeTertiary: '#71afe5',
		themeSecondary: '#2b88d8',
		themeDarkAlt: '#106ebe',
		themeDark: '#005a9e',
		themeDarker: '#004578',
		neutralLighterAlt: '#3c3c3c',
		neutralLighter: '#444444',
		neutralLight: '#515151',
		neutralQuaternaryAlt: '#595959',
		neutralQuaternary: '#5f5f5f',
		neutralTertiaryAlt: '#7a7a7a',
		neutralTertiary: '#c8c8c8',
		neutralSecondary: '#d0d0d0',
		neutralSecondaryAlt: '#d0d0d0',
		neutralPrimaryAlt: '#dadada',
		neutralPrimary: '#ffffff',
		neutralDark: '#f4f4f4',
		black: '#f8f8f8',
		white: '#333333',
	},
});

export const otherTheme = {};
